### PR TITLE
feature/jwt secrets

### PR DESCRIPTION
**Pull request by pieveee**
Supersedes pull request #14 

Additional changes:

- Removed decentralised JWT secret definition into a single Kubernetes secret reference

```yaml
jwt:
  secretName: "YOUR_JWT_SECRET_NAME"
```

- Added a little "hack" for Kong container to overwrite env placeholders `SUPABASE_ANON_KEY` and `SUPABASE_SERVICE_KEY` at container runtime
- Adjusted documentation accordingly

### CODE REVIEW

**Comment by pieveee** [comment]
@icrotz @milanvanschaik Is this repo still actively maintained? I would love to contribute and bring this project a step forward. Also to remove the "Comming soon" section in the [official documentation](https://supabase.com/docs/guides/hosting/overview) ;)

image

**Comment by icrotz** [comment]
I don't have the right to review and merge pull requests

**Comment by pieveee** [comment]
Who has it then? 😅

**Comment by milanvanschaik** [comment]
> @icrotz @milanvanschaik Is this repo still actively maintained? I would love to contribute and bring this project a step forward. Also to remove the "Comming soon" section in the [official documentation](https://supabase.com/docs/guides/hosting/overview) ;)
> 
> 
> 
> image
> 
> 

Sure think! Thanks for your PR! I'll look into it ASAP.

**Comment by pieveee** [comment]
@milanvanschaik Perfect! I made some adjustments and going to merge my PRs into one. I will close this one and come up with the new one in a minute.

**Pull request closed without merging**
