### PR TITLE
Several improvements and new features

### PR DESCRIPTION
**Pull request by pieveee**
I improved several configuration options as listed below.

**Secrets**
Moved direct configuration of confidential data into Kubernetes secrets and added the ability to reference the secrets in `values.yaml`: 

```yaml
jwt:
  secretName: "demo-supabase-jwt"

smtp:
  secretName: "demo-supabase-smtp"

db:
  secretName: "demo-supabase-db"
```

This affects JWT, Postgres and SMTP credentials.

**Additional Volumes / Custom TLS Certificates**
Furthermore, I added the ability to define additional volumes to every service: 

```yaml
  volumeMounts:
    - name: volume_name
      mountPath: /path/to/my/secret
  volumes:
    - name: volume_name
      secret:
        defaultMode: 733
        secretName: my_secret
        items:
        - key: my_secret.txt
          path: name_of_file_in_container.txt
```

This is extremely useful (and even required) when using self-signed certificates, as the CA certificate needs to be configured respectively referenced on the 'client'.

**Further Improvements**
Additional changes were made in terms of aligning configuration options in a common sense. For example, the DB connection parameters are now for every service the same (`DB_HOST`, `DB_PORT`. `DB_DRIVER`. `DB_NAME`. `DB_SSL`).

### CODE REVIEW

**Comment by pieveee** [comment]
Here we go @milanvanschaik 📦

**Comment by elvise** [comment]
@pieveee great PR!

are you going to merge ?

**Comment by pieveee** [comment]
@elvise Unfortunately, I don't have write access to this repository and can't merge. @milanvanschaik should be able to do that! 🚀

**Comment by elvise** [comment]
> @elvise Unfortunately, I don't have write access to this repository and can't merge. @milanvanschaik should be able to do that! 🚀 

@milanvanschaik merge ? 🙂

**Comment by milanvanschaik** [comment]
@pieveee @elvise Sorry for the lack on review from my side. This PR has been open for way too long.

@pieveee Thanks for the great work!

I'll merge it! Haven't found the time to look at the other PRs in the repo yet, and how they play with this one. I'll try to find some time.

**Pull request merged**
